---
save_emails_in: outlook # outlook: Default | gmail
delete_email_after_transfer: true # true: default | false
sync_unread_emails: true # true: default | false
sync_emails_folder: # List of folders from which emails will be saved
  - Inbox
  - Draft
  - All Mail
save_emails_folder: # List of folder to which emails will be saved
  - Inbox
  - Inbox.Draft
  - Archive

# save_emails_folder and sync_emails folders must be listed respectively i.e.
# for Sync Inbox to Inbox
# sync_emails_folder:
#   - Inbox
# save_emails_folder:
#   - Inbox